language: go

go:
  # go 1.10.x does no longer work because of Alex Edwards scs go getting...
  # - 1.10.2 
  # - 1.11
  - 1.12
  # - tip

os:
  - linux
  # - osx
  
services:
  # - mysql

sudo: false

addons:
  apt:
    packages:
    - wget

  
env:
  matrix:
    - DATASOURCE1=travis   SQL_PW=""    GO111MODULE=on 

before_install:
  # - go get -v github.com/golang/lint/golint


install:
  # Adding Godeps dependencies to GOPATH and PATH
  # - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  # - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  # - go get -u github.com/zew/go-questionnaire
  - go get -t ./...  
  - chmod 777 app-bucket
  - mv app-bucket/config-example.json  app-bucket/config.json
  - mv app-bucket/logins-example.json  app-bucket/logins.json
  - touch ./templates/site.css

before_script:
  # - mysql -e 'create database exceldb_test;'
  # - go vet ./...

script:
  #- env GO111MODULE=on go build
  #- env GO111MODULE=on go test
  - go test -v ./...

notifications:
  email: false
