language: go

go:
  # - 1.10.2 
  - 1.13
  # - tip

os:
  - linux
  # - osx
  
services:
  # - mysql

sudo: false

addons:
  apt:
    packages:
    - wget
  
env:
  matrix:
    # CODECOV_TOKEN only needed for private repos
    - DATASOURCE1=travis   SQL_PW=""    GO111MODULE=on   CODECOV_TOKEN="955a339e-2881-433f-9dca-bb3c89c86037"

before_install:
  # - go get -v github.com/golang/lint/golint
  # codecov.io requirement:
  - go get -t -v ./...


install:
  # - go get -t ./...  
  # Adding Godeps dependencies to GOPATH and PATH
  # - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  # - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  # - go get -u github.com/zew/go-questionnaire
  - chmod 777 app-bucket
  - mv app-bucket/config-example.json  app-bucket/config.json
  - mv app-bucket/logins-example.json  app-bucket/logins.json
  - touch ./templates/site.css

before_script:
  # - mysql -e 'create database exceldb_test;'
  # - go vet ./...

script:
  # - go test -v ./...
  # codecov.io replacement:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

notifications:
  email: false

after_success:
  # codecov.io requirement:
  - bash <(curl -s https://codecov.io/bash)